# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "10.11.10.11"
  config.vm.provision 'shell', path: 'bootstrap.sh'
  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096 #MB
  end
  config.vm.synced_folder '../..', '/vagrant'
end
